export type LangKey = 'en' | 'zh' | 'ja' | 'hi' | 'th';
export const languages = {
    en: {
        home: 'Home',
        search: 'Search',
        post: 'Post',
        notifications: 'Notifications',
        profile: 'Profile',
        darkMode: 'Dark Mode',
        language: 'Language',
        appName: 'Civic Salon',
        user: 'User',
        story: 'story',
        avatar: 'avatar',
        hoursAgo: 'hours ago',
        postContent: 'This is the post content. Text goes here.',
        postImage: 'Post image',
        like: 'Like',
        comment: 'Comment',
        share: 'Share',
        menu: 'Menu',
        messages: 'Messages',
        settings: 'Settings',
        searchPlaceholder: 'Search...',
        createPost: 'Create a new post',
        postPlaceholder: 'What\'s on your mind?',
        submit: 'Submit',
        back: 'Back',
        replies: 'Replies',
        addComment: 'Add a comment...',
        aiButton: 'Insights',
        background: 'Background',
        civicThoughts: 'Civic Thoughts',
        more: 'expand',
        less: 'collapse',
        loading: 'Processing...',
        chatAI: 'AI',
        chatPlaceholder: 'Ask me anything...',
        send: 'Send',
        discussBackground: 'Explore Background',
        discussCivicThoughts: 'Discuss Thoughts',
    },
    zh: {
        home: '首頁',
        search: '搜尋',
        post: '發文',
        notifications: '通知',
        profile: '個人檔案',
        darkMode: '深色模式',
        language: '語言',
        appName: '社交應用',
        user: '用戶',
        story: '故事',
        avatar: '頭像',
        hoursAgo: '小時前',
        postContent: '這是貼文內容。文字在這裡。',
        postImage: '貼文圖片',
        like: '讚',
        comment: '評論',
        share: '分享',
        menu: '選單',
        messages: '訊息',
        settings: '設定',
        searchPlaceholder: '搜尋...',
        createPost: '創建新貼文',
        postPlaceholder: '你在想什麼？',
        submit: '提交',
        back: '返回',
        replies: '回覆',
        addComment: '添加評論...',
        aiButton: '洞察',
        background: '背景',
        civicThoughts: '社会影响',
        more: '展开',
        less: '收起',
        loading: '处理中...',
        chatAI: 'AI助手',
        chatPlaceholder: '问我任何问题...',
        send: '发送',
        discussBackground: '探索背景',
        discussCivicThoughts: '讨论影响',
    },
    ja: {
        home: 'ホーム',
        search: '検索',
        post: '投稿',
        notifications: '通知',
        profile: 'プロフィール',
        darkMode: 'ダークモード',
        language: '言語',
        appName: 'Civic Salon',
        user: 'ユーザー',
        story: 'ストーリー',
        avatar: 'アバター',
        hoursAgo: '時間前',
        postContent: 'これは投稿の内容です。ここにテキストが入ります。',
        postImage: '投稿画像',
        like: 'いいね！',
        comment: 'コメント',
        share: 'シェア',
        menu: 'メニュー',
        messages: 'メッセージ',
        settings: '設定',
        searchPlaceholder: '検索...',
        createPost: '新しい投稿を作成',
        postPlaceholder: '何を考えていますか？',
        submit: '送信',
        back: '戻る',
        replies: '返信',
        addComment: 'コメントを追加...',
        aiButton: '洞察',
        background: '背景',
        civicThoughts: '社会的影響',
        more: '展開',
        less: '折りたたむ',
        loading: '処理中...',
        chatAI: 'AIアシスタント',
        chatPlaceholder: '何でも聞いてください...',
        send: '送信',
        discussBackground: '背景を探る',
        discussCivicThoughts: '影響を議論',
    },
    hi: {
        home: 'होम',
        search: 'खोज',
        post: 'पोस्ट',
        notifications: 'सूचनाएँ',
        profile: 'प्रोफ़ाइल',
        darkMode: 'डार्क मोड',
        language: 'भाषा',
        appName: 'Civic Salon',
        user: 'उपयोगकर्ता',
        story: 'कहानी',
        avatar: 'अवतार',
        hoursAgo: 'घंटे पहले',
        postContent: 'यह पोस्ट सामग्री है। यहाँ टेक्स्ट जाता है।',
        postImage: 'पोस्ट छवि',
        like: 'पसंद',
        comment: 'टिप्पणी',
        share: 'साझा करें',
        menu: 'मेनू',
        messages: 'संदेश',
        settings: 'सेटिंग्स',
        searchPlaceholder: 'खोजें...',
        createPost: 'नई पोस्ट बनाएं',
        postPlaceholder: 'आप क्या सोच रहे हैं?',
        submit: 'सबमिट करें',
        back: 'वापस',
        replies: 'जवाब',
        addComment: 'टिप्पणी जोड़ें...',
        aiButton: 'अंतर्दृष्टि',
        background: 'पृष्ठभूमि',
        civicThoughts: 'सामाजिक प्रभाव',
        more: 'विस्तार',
        less: 'संक्षेप',
        loading: 'प्रक्रिया जारी...',
        chatAI: 'AI सहायक',
        chatPlaceholder: 'कुछ भी पूछें...',
        send: 'भेजें',
        discussBackground: 'पृष्ठभूमि की खोज',
        discussCivicThoughts: 'प्रभाव पर चर्चा',
    },
    th: {
        home: 'หน้าแรก',
        search: 'ค้นหา',
        post: 'โพสต์',
        notifications: 'การแจ้งเตือน',
        profile: 'โปรไฟล์',
        darkMode: 'โหมดมืด',
        language: 'ภาษา',
        appName: 'Civic Salon',
        user: 'ผู้ใช้',
        story: 'สตอรี่',
        avatar: 'รูปโปรไฟล์',
        hoursAgo: 'ชั่วโมงที่แล้ว',
        postContent: 'นี่คือเนื้อหาโพสต์ ข้อความอยู่ที่นี่',
        postImage: 'รูปภาพโพสต์',
        like: 'ถูกใจ',
        comment: 'แสดงความคิดเห็น',
        share: 'แชร์',
        menu: 'เมนู',
        messages: 'ข้อความ',
        settings: 'การตั้งค่า',
        searchPlaceholder: 'ค้นหา...',
        createPost: 'สร้างโพสต์ใหม่',
        postPlaceholder: 'คุณกำลังคิดอะไรอยู่?',
        submit: 'ส่ง',
        back: 'กลับ',
        replies: 'การตอบกลับ',
        addComment: 'เพิ่มความคิดเห็น...',
        aiButton: 'ข้อมูลเชิงลึก',
        background: 'บริบท',
        civicThoughts: 'ผลกระทบทางสังคม',
        more: 'ขยาย',
        less: 'ย่อ',
        loading: 'กำลังประมวลผล...',
        chatAI: 'ผู้ช่วย AI',
        chatPlaceholder: 'ถามอะไรก็ได้...',
        send: 'ส่ง',
        discussBackground: 'สำรวจบริบท',
        discussCivicThoughts: 'อภิปรายผลกระทบ',
    },
}
