version: '3.8'
services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - WORKSPACE_URL=${WORKSPACE_URL}
      - SP_CLIENT_ID=${SP_CLIENT_ID}
      - SP_CLIENT_SECRET=${SP_CLIENT_SECRET}
      - DATABRICKS_TOKEN=${DATABRICKS_TOKEN}
    volumes:
      - .:/app
    restart: unless-stopped